// Generated by gencpp from file kmriiwa_msgs/LBRStatus.msg
// DO NOT EDIT!


#ifndef KMRIIWA_MSGS_MESSAGE_LBRSTATUS_H
#define KMRIIWA_MSGS_MESSAGE_LBRSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kmriiwa_msgs
{
template <class ContainerAllocator>
struct LBRStatus_
{
  typedef LBRStatus_<ContainerAllocator> Type;

  LBRStatus_()
    : header()
    , motion_enabled(false)
    , axes_mastered(false)
    , axes_gms_referenced(false)
    , axes_position_referenced(false)
    , safety_state_enabled(false)  {
    }
  LBRStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motion_enabled(false)
    , axes_mastered(false)
    , axes_gms_referenced(false)
    , axes_position_referenced(false)
    , safety_state_enabled(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _motion_enabled_type;
  _motion_enabled_type motion_enabled;

   typedef uint8_t _axes_mastered_type;
  _axes_mastered_type axes_mastered;

   typedef uint8_t _axes_gms_referenced_type;
  _axes_gms_referenced_type axes_gms_referenced;

   typedef uint8_t _axes_position_referenced_type;
  _axes_position_referenced_type axes_position_referenced;

   typedef uint8_t _safety_state_enabled_type;
  _safety_state_enabled_type safety_state_enabled;





  typedef boost::shared_ptr< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> const> ConstPtr;

}; // struct LBRStatus_

typedef ::kmriiwa_msgs::LBRStatus_<std::allocator<void> > LBRStatus;

typedef boost::shared_ptr< ::kmriiwa_msgs::LBRStatus > LBRStatusPtr;
typedef boost::shared_ptr< ::kmriiwa_msgs::LBRStatus const> LBRStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator1> & lhs, const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motion_enabled == rhs.motion_enabled &&
    lhs.axes_mastered == rhs.axes_mastered &&
    lhs.axes_gms_referenced == rhs.axes_gms_referenced &&
    lhs.axes_position_referenced == rhs.axes_position_referenced &&
    lhs.safety_state_enabled == rhs.safety_state_enabled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator1> & lhs, const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kmriiwa_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1e9bf004da750115463ceb70e37bbcd";
  }

  static const char* value(const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1e9bf004da75011ULL;
  static const uint64_t static_value2 = 0x5463ceb70e37bbcdULL;
};

template<class ContainerAllocator>
struct DataType< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kmriiwa_msgs/LBRStatus";
  }

  static const char* value(const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool motion_enabled\n"
"bool axes_mastered\n"
"bool axes_gms_referenced\n"
"bool axes_position_referenced\n"
"bool safety_state_enabled\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motion_enabled);
      stream.next(m.axes_mastered);
      stream.next(m.axes_gms_referenced);
      stream.next(m.axes_position_referenced);
      stream.next(m.safety_state_enabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LBRStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kmriiwa_msgs::LBRStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kmriiwa_msgs::LBRStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motion_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motion_enabled);
    s << indent << "axes_mastered: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.axes_mastered);
    s << indent << "axes_gms_referenced: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.axes_gms_referenced);
    s << indent << "axes_position_referenced: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.axes_position_referenced);
    s << indent << "safety_state_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.safety_state_enabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KMRIIWA_MSGS_MESSAGE_LBRSTATUS_H
