<?xml version="1.0" ?>
<sdf version="1.6">
  <model name="tormach_like_lathe_blocky">
    <static>true</static>

    <!-- Units: meters -->
    <!-- Base block: 46x38x31.5 in => 1.1684 x 0.9652 x 0.8001 -->
    <!-- Trapezoid: height 33 in => 0.8382; full width 0.9652; base length 1.1684; top length 0.5842 -->
    <!-- Side box: 10.5 x 22 x 29 in => 0.2667 x 0.5588 x 0.7366 -->
    <!-- Gap: 2 in => 0.0508 -->

    <link name="body">

      <!-- ================= Base cabinet (cuboid) ================= -->
      <collision name="base_col">
        <pose>0 0 0.40005 0 0 0</pose>
        <geometry><box><size>1.1684 0.9652 0.8001</size></box></geometry>
      </collision>
      <visual name="base_vis">
        <pose>0 0 0.40005 0 0 0</pose>
        <geometry><box><size>1.1684 0.9652 0.8001</size></box></geometry>
        <material>
          <ambient>0.18 0.18 0.19 1</ambient>
          <diffuse>0.40 0.40 0.43 1</diffuse>
          <specular>0.7 0.7 0.8 1</specular>
        </material>
      </visual>

      <!-- ================= Trapezoid enclosure (right-angled back) ================= -->
      <collision name="trap_col">
        <pose>0.0 0.4826 0.8001 1.57079632679 0 0</pose>
        <geometry>
          <polyline>
            <height>0.9652</height>
            <point>-0.5842 0.0</point>
            <point> 0.5842 0.0</point>
            <point> 0.2921 0.8382</point>
            <point>-0.5842 0.8382</point>
          </polyline>
        </geometry>
      </collision>
      <visual name="trap_vis">
        <pose>0.0 0.4826 0.8001 1.57079632679 0 0</pose>
        <geometry>
          <polyline>
            <height>0.9652</height>
            <point>-0.5842 0.0</point>
            <point> 0.5842 0.0</point>
            <point> 0.2921 0.8382</point>
            <point>-0.5842 0.8382</point>
          </polyline>
        </geometry>
        <material>
          <ambient>0.20 0.20 0.22 1</ambient>
          <diffuse>0.60 0.60 0.63 1</diffuse>
          <specular>0.8 0.8 0.9 1</specular>
        </material>
      </visual>

            <!-- ================= Side box (rotated, wide face toward front) =================
           After rotation (yaw 90°):
             - X size = 0.5588  (faces front)
             - Y size = 0.2667  (depth)
             - Z size = 0.7366  (height)
           Top aligns with base top: z_center = 0.4318
           2" gap: base left face at y=-0.4826; inner face of side box at y=-0.5334
             => side box center y = -(0.5334 + 0.2667/2) = -0.6668
           Position: near front → x_center = +0.5842 - 0.5588/2 = 0.3048
      -->
      <collision name="sidebox_col">
        <pose>0.3048 -0.6668 0.4318 0 0 1.5708</pose>
        <geometry><box><size>0.2667 0.5588 0.7366</size></box></geometry>
      </collision>
      <visual name="sidebox_vis">
        <pose>0.3048 -0.6668 0.4318 0 0 1.5708</pose>
        <geometry><box><size>0.2667 0.5588 0.7366</size></box></geometry>
        <material>
          <ambient>0.16 0.16 0.16 1</ambient>
          <diffuse>0.32 0.32 0.34 1</diffuse>
          <specular>0.6 0.6 0.7 1</specular>
        </material>
      </visual>

      

           <!-- ================= Cylindrical rod connector =================
           Orientation: axis along Y, so flat circular faces contact cube and side box.
           Length = 0.0508 (2" gap), radius = 0.02 (~0.8").
           Position: x = 0.3048 (aligned with side box), 
                     y = -0.5080 (center between faces),
                     z = 0.7493 (2" below top).
           Rotation: roll 90° (about X) so cylinder extends along Y.
      -->
     <!-- Cylindrical rod at top-front corner, 2" below cube top -->
      <collision name="rod_col">
        <pose>0.5842 -0.5080 0.7493 1.5708 0 0</pose>
        <geometry>
          <cylinder>
            <radius>0.02</radius>
            <length>0.0508</length>
          </cylinder>
        </geometry>
      </collision>
      <visual name="rod_vis">
        <pose>0.5842 -0.5080 0.7493 1.5708 0 0</pose>
        <geometry>
          <cylinder>
            <radius>0.02</radius>
            <length>0.0508</length>
          </cylinder>
        </geometry>
        <material>
          <ambient>0.25 0.25 0.25 1</ambient>
          <diffuse>0.55 0.55 0.58 1</diffuse>
          <specular>0.8 0.8 0.9 1</specular>
        </material>
      </visual>


    </link>
  </model>
</sdf>
